import 'package:watch_track/data/models/movie_model.dart';

final List<Movie> mockMovies = [
  Movie(
    id: '1',
    title: 'Neon Odyssey',
    overview: 'In a dystopian future where artificial intelligence controls the neon-lit megalopolis, a rogue hacker discovers a hidden code that could either liberate humanity or lead to its ultimate destruction. As he navigates the dangerous underworld of the city, he must decide who to trust in a world where nothing is as it seems.',
    posterPath: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=2070&auto=format&fit=crop',
    backdropPath: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop',
    rating: 8.7,
    releaseDate: '2024',
    runtime: '142 MIN',
    ageRating: 'PG-13',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    cast: [
      Cast(id: 'c1', name: 'Elias Thorne', character: 'Jack Vance', profilePath: 'https://i.pravatar.cc/150?u=elias'),
      Cast(id: 'c2', name: 'Lyra Quinn', character: 'Cipher', profilePath: 'https://i.pravatar.cc/150?u=lyra'),
      Cast(id: 'c3', name: 'Marcus Ray', character: 'The Architect', profilePath: 'https://i.pravatar.cc/150?u=marcus'),
    ],
  ),
  Movie(
    id: '2',
    title: 'Interstellar Odyssey',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival. As they face the vast unknown, they must confront their deepest fears and the reality of time dilation.',
    posterPath: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=2094&auto=format&fit=crop',
    backdropPath: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=2072&auto=format&fit=crop',
    rating: 8.9,
    releaseDate: '2024',
    runtime: '2h 45m',
    ageRating: 'PG-13',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    cast: [
      Cast(id: 'c4', name: 'Cooper', character: 'Pilot', profilePath: 'https://i.pravatar.cc/150?u=cooper'),
      Cast(id: 'c5', name: 'Amelia', character: 'Scientist', profilePath: 'https://i.pravatar.cc/150?u=amelia'),
    ],
  ),
  Movie(
    id: '3',
    title: 'Neon Horizons',
    overview: 'A futuristic detective investigates a series of murders in a city where memories can be bought and sold.',
    posterPath: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=2070&auto=format&fit=crop',
    backdropPath: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=2070&auto=format&fit=crop',
    rating: 8.4,
    releaseDate: '2023',
    runtime: '120 MIN',
    ageRating: 'R',
    genres: ['Sci-Fi', 'Mystery'],
    cast: [],
  ),
  Movie(
    id: '4',
    title: 'Dust & Fury',
    overview: 'In a post-apocalyptic wasteland, a lone warrior searches for the man who destroyed his village.',
    posterPath: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=2025&auto=format&fit=crop',
    backdropPath: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=2070&auto=format&fit=crop',
    rating: 7.9,
    releaseDate: '2024',
    runtime: '115 MIN',
    ageRating: 'R',
    genres: ['Action', 'Adventure'],
    cast: [],
  ),
];

final List<Movie> mockSeries = [
  Movie(
    id: 's1',
    title: 'The Fracture',
    overview: 'A group of survivors must navigate a world where the laws of physics are breaking down.',
    posterPath: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=2070&auto=format&fit=crop',
    backdropPath: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=2184&auto=format&fit=crop',
    rating: 6.8,
    releaseDate: '2024',
    runtime: '8 Episodes',
    ageRating: 'TV-MA',
    genres: ['Sci-Fi', 'Drama'],
    cast: [],
    isMovie: false,
  ),
];
