import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:watch_track/features/update/data/models/update_model.dart';
import 'package:watch_track/features/update/data/repositories/update_repository.dart';

class AdminUpdateScreen extends StatefulWidget {
  const AdminUpdateScreen({super.key});

  @override
  State<AdminUpdateScreen> createState() => _AdminUpdateScreenState();
}

class _AdminUpdateScreenState extends State<AdminUpdateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _versionNameController = TextEditingController();
  final _versionCodeController = TextEditingController();
  final _releaseNotesController = TextEditingController();
  final _apkUrlController = TextEditingController();
  final _apkSizeController = TextEditingController();
  final _minSupportedVersionController = TextEditingController();
  final _changelogController = TextEditingController();
  final _sha256Controller = TextEditingController();
  
  bool _forceUpdate = false;
  bool _isActive = true;
  bool _isLoading = false;

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    
    setState(() => _isLoading = true);
    
    try {
      final repository = context.read<UpdateRepository>();
      final update = UpdateModel(
        id: '', // Generated by Appwrite
        versionName: _versionNameController.text,
        versionCode: int.parse(_versionCodeController.text),
        releaseNotes: _releaseNotesController.text,
        apkUrl: _apkUrlController.text,
        apkSize: _apkSizeController.text,
        forceUpdate: _forceUpdate,
        releaseDate: DateTime.now(),
        minSupportedVersion: int.parse(_minSupportedVersionController.text),
        changelog: _changelogController.text.split('\\n').where((s) => s.isNotEmpty).toList(),
        isActive: _isActive,
        sha256Hash: _sha256Controller.text.isNotEmpty ? _sha256Controller.text : null,
      );
      
      await repository.createUpdate(update);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Update published successfully!')));
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: \$e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Admin Update Management'),
        backgroundColor: Colors.blueAccent,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _versionNameController,
                decoration: const InputDecoration(labelText: 'Version Name (e.g. 2.3.0)'),
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _versionCodeController,
                decoration: const InputDecoration(labelText: 'Version Code (e.g. 230)'),
                keyboardType: TextInputType.number,
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _apkUrlController,
                decoration: const InputDecoration(labelText: 'APK Download URL'),
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _apkSizeController,
                decoration: const InputDecoration(labelText: 'APK Size (e.g. 45 MB)'),
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _minSupportedVersionController,
                decoration: const InputDecoration(labelText: 'Min Supported Version Code'),
                keyboardType: TextInputType.number,
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _releaseNotesController,
                decoration: const InputDecoration(labelText: 'Release Notes'),
                maxLines: 3,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _changelogController,
                decoration: const InputDecoration(labelText: 'Changelog (One per line)'),
                maxLines: 4,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _sha256Controller,
                decoration: const InputDecoration(labelText: 'SHA256 Hash (Optional)'),
              ),
              const SizedBox(height: 12),
              SwitchListTile(
                title: const Text('Force Update'),
                value: _forceUpdate,
                onChanged: (v) => setState(() => _forceUpdate = v),
              ),
              SwitchListTile(
                title: const Text('Is Active'),
                value: _isActive,
                onChanged: (v) => setState(() => _isActive = v),
              ),
              const SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                height: 48,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submit,
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.blueAccent),
                  child: _isLoading 
                    ? const CircularProgressIndicator(color: Colors.white) 
                    : const Text('Publish Release', style: TextStyle(color: Colors.white)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
